import { Inter } from "next/font/google";

import LogoutButton from "../components/LogoutButton";
import { getServerSession } from "next-auth"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = { 
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="bg-gray-100 py-4  shadow-lg shadow-gray-500/50 mb-1">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="https://municca.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
        <img class="h-8" src="https://www.municca.com/wp-content/uploads/2023/04/Prancheta-1-copia-2-e1682785551158.png" srcset="https://www.municca.com/wp-content/uploads/2023/04/Prancheta-1-copia-2-e1682785551158.png 2x" alt="Municca" />
      
        </a>
        
        { session && 
        <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            <LogoutButton  />
        </div>
        }
      </div>
      </nav>
        {children}
        </body>
    </html>
  );
}
